services:
  suricata:
    image: jasonish/suricata:latest
    container_name: specula-suricata
    network_mode: host
    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE

    environment:
      TZ: ${TZ}

    command:
      - -i
      - ${SURICATA_INTERFACE}
      - -c
      - /etc/suricata/suricata.yaml

    volumes:
      - ./etc:/etc/suricata
      - ../rules:/var/lib/suricata/rules
      - ../logs:/var/log/suricata