from detection.action_catalog import (
    AUTH_INVESTIGATE,
    FILE_INTEGRITY_INVESTIGATE,
    MALWARE_INVESTIGATE,
    MISCONFIG_REMEDIATE,
    PRIV_ESC_INVESTIGATE,
    SYSTEM_ACTIVITY_REVIEW,
    TELEMETRY_RESTORE,
    VULN_REMEDIATE,
)

WAZUH_RULE_MAPPINGS = [
    {
        "rule_ids": {"5710", "5712", "5715", "5720", "5725"},
        "category": "authentication",
        "name": "Tentative de brute force SSH",
        "summary": "Des échecs d'authentification SSH ou des tentatives répétées ont été détectés",
        "severity": "high",
        "recommended_actions": AUTH_INVESTIGATE,
        "tags": ["ssh", "authentication", "access"],
    },
    {
        "rule_ids": {"4625", "4624", "4648", "4672", "4740"},
        "category": "authentication",
        "name": "Événement d'authentification Windows",
        "summary": "Un événement d'authentification Windows potentiellement sensible a été détecté",
        "severity": "medium",
        "recommended_actions": AUTH_INVESTIGATE,
        "tags": ["windows", "authentication", "access"],
    },
    {
        "rule_ids": {"554", "555", "4728", "4732"},
        "category": "privilege_escalation",
        "name": "Élévation de privilèges détectée",
        "summary": "Une action liée à des privilèges élevés a été détectée",
        "severity": "high",
        "recommended_actions": PRIV_ESC_INVESTIGATE,
        "tags": ["privilege", "sudo", "admin"],
    },
    {
        "rule_ids": {"4720", "4726", "4738", "4781"},
        "category": "system_activity",
        "name": "Modification de compte détectée",
        "summary": "Un compte utilisateur a été créé, modifié, renommé ou supprimé",
        "severity": "high",
        "recommended_actions": SYSTEM_ACTIVITY_REVIEW,
        "tags": ["identity", "account", "system"],
    },
    {
        "rule_ids": {"550", "551", "552", "553"},
        "category": "file_integrity",
        "name": "Modification de fichier critique détectée",
        "summary": "Un fichier surveillé a été créé, modifié, supprimé ou a changé d'attribut",
        "severity": "high",
        "recommended_actions": FILE_INTEGRITY_INVESTIGATE,
        "tags": ["fim", "file", "integrity"],
    },
    {
        "rule_ids": {"592", "593"},
        "category": "system_activity",
        "name": "Activité processus sensible détectée",
        "summary": "Une activité de processus potentiellement sensible a été observée",
        "severity": "medium",
        "recommended_actions": SYSTEM_ACTIVITY_REVIEW,
        "tags": ["process", "execution", "system"],
    },
    {
        "rule_ids": {"517", "1102", "4719"},
        "category": "misconfiguration",
        "name": "Altération de journalisation ou d'audit détectée",
        "summary": "Une modification de politique d'audit ou un effacement de journaux a été détecté",
        "severity": "critical",
        "recommended_actions": MISCONFIG_REMEDIATE,
        "tags": ["audit", "logging", "tampering"],
    },
    {
        "rule_ids": {"100001", "100002"},
        "category": "malware",
        "name": "Indicateur malware détecté",
        "summary": "Une signature ou un indicateur potentiellement malveillant a été détecté",
        "severity": "critical",
        "recommended_actions": MALWARE_INVESTIGATE,
        "tags": ["malware", "ioc", "yara"],
    },
    {
        # IDs Wazuh vulnerability-detector : 23501 (info) → 23506 (critical)
        # + marqueur catégorie pour le matcher
        "rule_ids": {
            "23501", "23502", "23503", "23504", "23505", "23506",
            "23507", "23508", "23509", "23510",
            "VULNERABILITY",
        },
        "category": "vulnerability",
        "name": "Vulnérabilité détectée",
        "summary": "Une vulnérabilité exploitable ou un composant vulnérable a été identifié sur cet actif",
        "severity": "high",
        "recommended_actions": VULN_REMEDIATE,
        "tags": ["vulnerability", "cve", "exposure"],
    },
    {
        "rule_ids": {"AGENT_ACTIVE", "AGENT_DISCONNECTED", "AGENT_INACTIVE", "AGENT_NEVER_CONNECTED"},
        "category": "telemetry",
        "name": "État de télémétrie de l'agent",
        "summary": "L'état de télémétrie d'un agent a changé ou nécessite une attention",
        "severity": "medium",
        "recommended_actions": TELEMETRY_RESTORE,
        "tags": ["telemetry", "agent", "coverage"],
    },
]